language: node_js
install:
  - yarn install --frozen-lockfile
script:
  - bash ./travis/gh-pages.sh
env:
  global:
  - ENCRYPTION_LABEL: "a5aa6a4fcd88"
  - COMMIT_AUTHOR_EMAIL: "sh@signalwerk.ch"
  - DEPLOY_DIR: "./sites/blog/public"
branches:
  only:
  - master
